---
site_name: SlipBox
site_description: Slipbox Vault
site_author: Jimmy Briggs
# site_url: https://vault.jimbrig.com
copyright: Copyright &copy; 2021 Jimmy Briggs
repo_url: https://github.com/jimbrig/Slipbox
repo_name: jimbrig/Slipbox
remote_branch: gh-pages
edit_uri: blob/main/docs
use_directory_urls: true
plugins:
  - search
  # - autolinks
  # - section-index
  # - mkdocs-newsletter
  - roamlinks
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
markdown_extensions:
  - toc:
      permalink: ⚑
      baselevel: 2
  - codehilite:
      linenums: false
      guess_lang: true
  - footnotes
  - abbr
  - admonition
  - meta
  - def_list
  # - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: "!!python/name:pymdownx.emoji.to_svg"
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.snippets
  # - pymdownx.superfences
  # - pymdownx.tabbed
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
# theme:
#   name: cinder
#   colorscheme: dracula
#   highlightjs: true
#  language: "en"
#   favicon: "obsidian.ico"
#   icon:
#     repo: fontawesome/brands/github
#   features:
#     - tabs
#     - search.highlight
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jimbrig
    - icon: fontawesome/solid/rss
      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index
